config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :tecgnologies
	accepts_nested_attributes_for :tecgnologies, 
								  allow_destroy: true,
								  reject_if: lambda { |attrs| attrs['name'].blank? }

	validates_presence_of :title, :body

	mount_uploader :thumb_image, PortfolioUploader
	mount_uploader :main_image, PortfolioUploader

	def self.angular
		where(subtitle: 'Angular')
	end

	def self.by_position
		order("position ASC")
	end

	scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

	def index
		@portfolio_item = Portfolio.by_position
	end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render body: nil
  end

  def angular
    @angular_portfolio_item = Portfolio.angular
  end

	def new 
		@portfolio_item = Portfolio.new
    3.times { @portfolio_item.tecgnologies.build }
	end

	def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: "Your portfolio item is now live." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "The record successfully updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def destroy

  	# Destroy/Delete the record
    @portfolio_item.destroy

    #Redirecty
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: "The record was removed." }
    end
  end

  private 

  def portfolio_params 
    params.require(:portfolio).permit(:title, 
                                      :subtitle,
                                      :body, 
                                      :main_image,
                                      :thumb_image,
                                      tecgnologies_attributes: [:id, :name, :_destroy]
                                      )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
	def image_generator(height:, width:)
	"https://via.placeholder.com/#{height}x#{width}"
	end

	def portfolio_img img, type
		if img.model.main_image? || img.model.thumb_image?
			img
		elsif type == 'thumb'
			image_generator(height: '350', width: '200')
		elsif type == 'main'
			image_generator(height: '600', width: '400')
		end
	end
end

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item) do |form| %>
<div class="row">
  <div class="col-md-6">
    <div class="mb-3">
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :subtitle, style: "display: block" %>
      <%= form.text_area :subtitle, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <label class="btn btn-primary">
        Upload a Main Image file <%= form.file_field :main_image, style: 'display:none;' %>
      </label>
    </div>

    <div class="mb-3">
      <label class="btn btn-primary">
        Upload a Thumb Image file <%= form.file_field :thumb_image, style: 'display:none;' %>
      </label>
    </div>
  </div>

  <div class="col-md-6">
    <div class="mb-3">
      <%= form.label :body, style: "display: block" %>
      <%= form.text_area :body, class: 'form-control', rows: 13 %>
    </div>
  </div>
</div>

  <hr>

  <div class="col-md-12">
    <h2>Technologies Used:</h2>
    <div>
      <%= form.fields_for :tecgnologies do |tecgnology_form| %>
        <%= render 'tecgnology_fields', f: tecgnology_form %>
      <% end %>
      <div>
        <%= link_to_add_association 'Add Technology', form, :tecgnologies %>
      </div>
    </div>

    <div class="mb-3 d-grid">
      <%= form.submit "Save Portfolio Item", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col" data-id="<%= portfolio_item.id %>">
  <div class="card shadow-sm">
    <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb') %>

    <div class="card-body">
      <h3 class="card-text">
      	<span><%= portfolio_item.title %></span>
  		</h3>
      <p class="card-text">
      	<span><%= portfolio_item.subtitle %></span>
  		</p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= button_to "View", portfolio_show_path(portfolio_item), method: :get, class: 'btn btn-sm btn-outline-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_tecgnology_fields.html.erb
<div class="mb-3 nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin) %>

<% @angular_portfolio_item.each do |portfolio_item| %>
	<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
	<p><%= portfolio_item.subtitle %></p>
	<p><%= portfolio_item.body %></p>
	<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
	<%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
	<%= button_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
	<h1>Edit this Portfolio Item</h1>

	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 <%= "sortable" if logged_in?(:site_admin) %>">

		<%= render partial: 'portfolio_item', collection: @portfolio_item %>

		</div>
	</div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
	<h1>Create a new Portfolio Item</h1>

	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
	<div class="row">
		<div class="col-md-7">
			<%= image_tag portfolio_img(@portfolio_item.main_image, 'main') %>
		</div>
		<div class="col-md-5">
			<h1><%= @portfolio_item.title %></h1>

			<hr>

			<em><%= @portfolio_item.subtitle %></em>s

			<p><%= @portfolio_item.body %></p>

			<hr>

			<h3>Technologies Used:</h3>

			<% @portfolio_item.tecgnologies.each do |t| %>
			<p><%= t.name %></p>
			<% end %>
			<% if logged_in?(:site_admin) %>
				<div class="">
					<%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' %>
				</div>
			<% end %>
		</div>
	</div>
</div>