config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mt-auto text-white-50">
        <p class="app-footer"><%= copyright_generator %></p>
</footer>

app/views/shared/_application_nav.html.erb
<header class="mb-auto">
  <div>
    <h3 class="float-md-start mb-0">Sebastian Guauque</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end app-nav">
      <%= nav_helper 'nav-link fw-bold py-1 px-0','span' %>
      <%= login_helper "nav-link fw-bold py-1 px-0" %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 fst-italic">Title of a longer featured blog post</h1>
    <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
    <p class="lead mb-0"><a href="#" class="text-white fw-bold">Continue reading...</a></p>
  </div>
</div>

<h3 class=" fst-italic">
  From the Firehose
</h3>

<p class="fst-italic border-bottom"><%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %></p>

app/views/shared/_blog_nav.html.erb
<div class="nav-scroller blog-header py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <%= nav_helper 'nav-link','span' %>
    <%= login_helper 'nav-link' %>
  </nav>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-md-4">
  <div class="position-sticky" style="top: 2rem;">
    <div class="p-4 mb-3 bg-light rounded">
      <h4 class="fst-italic">About</h4>
      <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
    </div>

    <div class="p-4">
      <h4 class="fst-italic">Elsewhere</h4>
      <ol class="list-unstyled social-links">
        <li><a href="#"><%= fa_icon "github"%></a></li>
        <li><a href="#"><%= fa_icon "facebook"%></a></li>
        <li><a href="#"><%= fa_icon "twitter"%></a></li>
        <li><a href="#"><%= fa_icon "instagram"%></a></li>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
      <div><%= link_to "Home", root_path %></div>
      <div><%= link_to "About Me", about_me_path %></div>
      <div><%= link_to "Contact", contact_path %></div>
      <div><%= link_to "Blog", blogs_path %></div>
      <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <%= link_to "View All Portfolio", portfolios_path %> |
      <a href="#">Back to top</a>
    </p>
    <%= copyright_generator %>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">My Portfolio</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
      <p>
        <%= link_to 'About Me', about_me_path, class: 'btn btn-primary my-2' %>
        <%= link_to 'Contact Me', contact_path, class: 'btn btn-secondary my-2' %>
      </p>
    </div>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white','li' %>
            <li><%= login_helper 'text-white' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Sebastian Guauque</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>